### ISSUE TITLE
ANSI colors not working after GraalVM native compilation

### ISSUE THREAD

**Issue by mBaratta96** [AvisoNovate/pretty#84]
Hello,
I've been trying to implement a TUI in Clojure, and I'd like to use your library to highlight parts of text. For example, I use a map to select a different style of different parts of texts:

```clojure
(def ^:private ^:const ANSI-CODES
  {:reset "[0m",
   :blue "[34m",
   :red "[31m",
   :green "[32m",
   :yellow "[33m",
   :cyan "[36m",
   :underline "[4m",
   :bold "[1m",
   :italic "[3m"})

(defn ^:private ansi
  [code]
  (str \u001b (get ANSI-CODES code (:reset ANSI-CODES))))
(defn ^:private style
  [s & codes]
  (str (apply str (map ansi codes)) s (ansi :reset)))

(def ^:private ^:const COLOR-TYPES
  {:link (fn [s] (compose [:blue.underlined s])),
   :song (fn [s] (compose [:green.italic s])),
   :album (fn [s] (style s :yellow :bold)),
   :band-name (fn [s] (style s :blue :italic)),
   :header (fn [s] (style s :red :bold)),
   :option (fn [index s]
             (str (style (str index ". ") :cyan :bold) (style s :bold)))})
```

Using the `compose` function, I can print ANSI characters easily when I run `lein run`:

![Schermata del 2023-05-08 08-47-42](https://user-images.githubusercontent.com/37810930/236754369-1c6eac83-9352-48f4-820d-9784108a2c04.png)

However, this doesn't work when I use GraalVM native image compilation:

![Schermata del 2023-05-08 08-48-15](https://user-images.githubusercontent.com/37810930/236754398-0aaa70cf-a0d2-4d16-86e2-1160e4e47a8c.png)

This is my `project.clj`:

```clojure
(defproject scaruffi_tui "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0",
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [hickory "0.7.1"]
                 [org.clj-commons/clj-http-lite "1.0.13"]
                 [io.aviso/pretty "1.4.2"]]
  :main scaruffi-tui.core
  :target-path "target/%s"
  :aliases {"native"
            ["shell"
             "native-image"
             "--report-unsupported-elements-at-runtime"
             "--initialize-at-build-time"
             "--no-server"
             "-jar"
             "./target/uberjar/scaruffi_tui-0.1.0-SNAPSHOT-standalone.jar"
             "-H:Name=./target/scaruffi"
             "--diagnostics-mode"
             "--enable-url-protocols=https"]}
  :profiles {:uberjar {:aot :all}, :dev {:plugins [[lein-shell "0.5.0"]]}})
```

**Comment by mBaratta96** [comment]
Tried to add the env variable, and it didn't work. I also printed the values of `ansi-output-enabled?`:

```
#object[clojure.core$_PLUS_ 0x6d968739 clojure.core$_PLUS_@6d968739] false
```

**Comment by mBaratta96** [comment]
Sorry. I, of course, misunderstood, `ENABLE_ANSI_COLORS` must be set *before* native compilation. With that, everything seems to work.

Thanks a lot!

**Comment by hlship** [comment]
That's problematic, that the behavior is "locked down" at Graal compile time, but I guess that make's sense for Graal ... but that's not good IMO because the whole point is for the behavior to adapt to its environment.  It feels like, when compiled for Graal, then "emit ANSI or not" decision should be made at runtime rather than during code compilation time the way it is done now.

In fact, this same behavior might exist during AOT compilation, not just Graal compilation.

**Comment by hlship** [comment]
That's problematic, that the behavior is "locked down" at Graal compile time, but I guess that make's sense for Graal ... but that's not good IMO because the whole point is for the behavior to adapt to its environment.  It feels like, when compiled for Graal, then "emit ANSI or not" decision should be made at runtime rather than during code compilation time the way it is done now.

In fact, this same behavior might exist during AOT compilation, not just Graal compilation.

**Comment by mBaratta96** [comment]
At the moment, the workaround works for my use case. However, if you want me to test your new solutions, no problem. Maybe starting from [System properties](https://www.graalvm.org/22.0/reference-manual/native-image/Properties/) could be an idea?

**Comment by hlship** [comment]
The goal is for all the constants to be the empty string if ANSI output is not available (and all the functions to return their input string unchanged).  However, that assumes the environment when executing is the same as when the Clojure code is compiled (and when the bytecode is pre-compiled by Graal).
